tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#40009b",
        "tertiary-dim": "#00d4ec",
        "outline-variant": "#48474c",
        "primary-fixed-dim": "#7a89ff",
        "on-tertiary-fixed": "#003840",
        "surface-container": "#19191e",
        "inverse-surface": "#fcf8fe",
        "secondary-container": "#5516be",
        "surface-container-low": "#131317",
        "surface": "#0e0e12",
        "background": "#0e0e12",
        "error": "#ff6e84",
        "tertiary-fixed": "#00e3fd",
        "secondary": "#ac8aff",
        "on-error-container": "#ffb2b9",
        "tertiary": "#81ecff",
        "surface-dim": "#0e0e12",
        "primary": "#9da7ff",
        "on-primary-fixed-variant": "#001490",
        "secondary-fixed": "#dac9ff",
        "surface-bright": "#2c2b32",
        "error-dim": "#d73357",
        "on-error": "#490013",
        "inverse-on-surface": "#555459",
        "on-tertiary-fixed-variant": "#005762",
        "tertiary-container": "#00e3fd",
        "on-surface-variant": "#acaab0",
        "on-tertiary": "#005762",
        "error-container": "#a70138",
        "outline": "#76757a",
        "on-secondary-container": "#d9c8ff",
        "on-primary": "#001597",
        "inverse-primary": "#3449e9",
        "on-primary-container": "#000f77",
        "primary-fixed": "#8c98ff",
        "on-surface": "#fcf8fe",
        "surface-container-high": "#1f1f25",
        "secondary-dim": "#8455ef",
        "surface-container-highest": "#25252b",
        "on-primary-fixed": "#000000",
        "on-secondary": "#280067",
        "on-secondary-fixed-variant": "#5f28c8",
        "primary-container": "#8c98ff",
        "primary-dim": "#4e62ff",
        "surface-variant": "#25252b",
        "surface-tint": "#9da7ff",
        "secondary-fixed-dim": "#ceb9ff",
        "surface-container-lowest": "#000000",
        "on-background": "#fcf8fe",
        "on-tertiary-container": "#004d57",
        "tertiary-fixed-dim": "#00d4ec"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
}
